// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fgcibeofaautnihcsiky.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZnY2liZW9mYWF1dG5paGNzaWt5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzgwNDc3OTcsImV4cCI6MjA1MzYyMzc5N30.D3NYnqiwJHEa7T2nHpzFROog-G5tZhuLIg2ReFSh2dw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);